name: Push_dev

on:
  push:
    branches:
      - main
      - sandbox
      
permissions:
      id-token: write
      contents: read


      

jobs: 
  deploy-infra:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      
    environment: prod
    env:
      TF_VAR_azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
      TF_VAR_azure_subscription_id : ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      TF_VAR_azure_tenant_id : ${{ secrets.AZURE_TENANT_ID }}
      TF_API_TOKEN : ${{ secrets.TF_API_TOKEN }}
      
#       TF_VAR_TFC_WORKLOAD_IDENTITY_AUDIENCE: "api://AzureADTokenExchange"
#       TFC_AZURE_PROVIDER_AUTH: true
#       TFC_AZURE_RUN_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      TF_VARS: "vars.tfvars"
      
    defaults:
      run:
        shell: bash
        working-directory: './iac'
        
        
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
      
    
        
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.9
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
        terraform_wrapper: false

#     # Log into Azure with OIDC integration
#     - name: 'Az CLI login'
#       uses: azure/login@v1
#       with:
#         client-id: $TF_VAR_azure_client_id
#         tenant-id: $TF_VAR_azure_tenant_id 
#         subscription-id: $TF_VAR_azure_subscription_id
      
  

#     # Run az commands to confirm sub access
#     - name: 'Run az commands'
#       run: |
#         az account show
             
    # Run Terraform init
    - name: Terraform Init
      id: init
      run: terraform init 
   
    - name: Terraform Format
      continue-on-error: true
      id: fmt
      run: terraform fmt --check
      
    - name: Terraform Validate
      id: validate
      run: terraform validate
      
    - name: Terraform Plan
      id: plan
      run: terraform plan --var-file=$TF_VARS
      continue-on-error: true
      
    # Run a Terraform apply
    - name: Terraform apply
      id: apply
      run: terraform apply --var-file=$TF_VARS -auto-approve
